[ALPS07713407] MET: fix undeclared function freezer_do_not_count
Follow commit f5d39b020809 ("freezer,sched: Rewrite core freezer logic")
to fix the following build breaks:

met_drv_v3/common/tinysys/v1/gpueb/gpueb_met_log.c:373:2:
error: call to undeclared function freezer_do_not_count;
iso c99 and later do not support implicit function declarations
[-wimplicit-function-declaration]
met_drv_v3/common/tinysys/v1/mcupm/mcupm_met_log.c:376:2:
error: call to undeclared function freezer_do_not_count;
iso c99 and later do not support implicit function declarations
[-wimplicit-function-declaration]
met_drv_v3/common/tinysys/v1/sspm/sspm_met_log.c:373:2:
error: call to undeclared function freezer_do_not_count;
iso c99 and later do not support implicit function declarations
[-wimplicit-function-declaration]
met_drv_v3/common/tinysys/v1/gpueb/gpueb_met_log.c:375:2:
error: call to undeclared function freezer_count;
iso c99 and later do not support implicit function declarations
[-wimplicit-function-declaration]
met_drv_v3/common/tinysys/v1/mcupm/mcupm_met_log.c:378:2:
error: call to undeclared function freezer_count;
iso c99 and later do not support implicit function declarations
[-wimplicit-function-declaration]
met_drv_v3/common/tinysys/v1/sspm/sspm_met_log.c:375:2:
error: call to undeclared function freezer_count;
iso c99 and later do not support implicit function declarations
[-wimplicit-function-declaration]

MTK-Commit-Id: 9bc2d0724c5932d95a4e599a266736cea153e7fc

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: If771c2193f4e240296a14da98c84dc65d9f0e972