[ALPS08631203] follow ARMV8_PMU_PMCR_N define remove
[Description]
Fix build error according to Commit "e72fc1229" (Merge 6cbf5b3105f31 ("Merge tag locking-core-2024-01-08 of git://git.kernel.org/pub/scm/linux/kernel/git/tip/tip") into aosp-android-mainline)

../vendor/mediatek/kernel_modules/met_drv_v3/common/v8_pmu_hw.c:238:58: error: use of undeclared identifier ARMV8_PMU_PMCR_N_SHIFT
  238 |         armv8_pmu.event_count[cpu] = ((read_sysreg(pmcr_el0) >> ARMV8_PMU_PMCR_N_SHIFT) & ARMV8_PMU_PMCR_N_MASK) + 1;
      |                                                                 ^
../vendor/mediatek/kernel_modules/met_drv_v3/common/v8_pmu_hw.c:238:84: error: use of undeclared identifier ARMV8_PMU_PMCR_N_MASK
  238 |         armv8_pmu.event_count[cpu] = ((read_sysreg(pmcr_el0) >> ARMV8_PMU_PMCR_N_SHIFT) & ARMV8_PMU_PMCR_N_MASK) + 1;
      |                                                                                           ^
2 errors generated.

../vendor/mediatek/kernel_modules/met_drv_v3/common/cpu_pmu.c:130:59: error: use of undeclared identifier ARMV8_PMU_PMCR_N_SHIFT
  130 |         *(cpu_pmu_num + core_id) = (read_sysreg(pmcr_el0) >> ARMV8_PMU_PMCR_N_SHIFT) & ARMV8_PMU_PMCR_N_MASK;
      |                                                              ^
../vendor/mediatek/kernel_modules/met_drv_v3/common/cpu_pmu.c:130:85: error: use of undeclared identifier ARMV8_PMU_PMCR_N_MASK
  130 |         *(cpu_pmu_num + core_id) = (read_sysreg(pmcr_el0) >> ARMV8_PMU_PMCR_N_SHIFT) & ARMV8_PMU_PMCR_N_MASK;
      |                                                                                        ^
2 errors generated.

[Test]
Build and Boot up

MTK-Commit-Id: 73f2c340ca1b5c5417c6ff7649b1435506436581

Change-Id: I00be26166981d464bceb655f9c37f124b9f0be26
Signed-off-by: PoShao Chen <poshao.chen@mediatek.com>
CR-Id: ALPS08631203
Feature: Kernel SI Operation