[ALPS08631203] follow strlcpy api remove
[Description]
Fix build error according to Commit "6fe236d7" (Merge 3cb9871f8160 ("Merge tag urgent-rcu.2024.01.24a of https://github.com/neeraju/linux";;) into android-mainline)

../vendor/mediatek/kernel_modules/met_drv_v3/common/tinysys/v1/mcupm/mcupm_met_log.c:647:2: error: call to undeclared library function strlcpy with type unsigned long (char *, const char *, unsigned long); ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  647 |         strlcpy(plog, buf, count+1);
      |         ^

../vendor/mediatek/kernel_modules/met_drv_v3/common/tinysys/v1/sspm/sspm_met_log.c:636:2: error: call to undeclared library function strlcpy with type unsigned long (char *, const char *, unsigned long); ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  636 |         strlcpy(plog, buf, count+1);
      |         ^

../vendor/mediatek/kernel_modules/met_drv_v3/common/tinysys/v1/gpueb/gpueb_met_log.c:629:2: error: call to undeclared library function strlcpy with type unsigned long (char *, const char *, unsigned long); ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  629 |         strlcpy(plog, buf, count+1);
      |         ^

../vendor/mediatek/kernel_modules/met_drv_v3/common/met_ptpod.c:91:3: error: call to undeclared library function strlcpy with type unsigned long (char *, const char *, unsigned long); ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   91 |                 strlcpy((*rg)[*rg_cnt].name, reg_name, sizeof((*rg)[*rg_cnt].name));
      |                 ^

[Test]
Build and Boot up

MTK-Commit-Id: 317926079fa66222d9f0dbd0f4a0848918ceb933

Signed-off-by: PoShao Chen <poshao.chen@mediatek.com>
CR-Id: ALPS08631203
Feature: Kernel SI Operation
Change-Id: Icd9d41b696712fdfbb29302552b51307a8df90a3