[ALPS08631203] met: fix build error due to mainline migration
[Description]
Fix build error according to Commit "4cf6336 Merge tag v6.10-rc1 into android-mainline"
../vendor/mediatek/kernel_modules/met_drv_v3/common/interface.c:1224:1: error: const type qualifier on return type has no effect [-Werror,-Wignored-qualifiers]
 1224 | const unsigned int met_get_chip_id(void)
      | ^~~~~
1 error generated.

[Test]
Build and Boot up

MTK-Commit-Id: a77da852cc9aef35ba4bb97b6165b0a66daf476b

Signed-off-by: PoShao Chen <poshao.chen@mediatek.com>
CR-Id: ALPS08631203
Feature: Kernel SI Operation
Change-Id: Ic26f361ee6178c7aac1b13e32986e0a514663840