[ALPS08631203] follow thermal_zone_device struct change
[Description]
Fix build error according to Commit "041a221 Merge f952b6c86309 ("Merge tag thermal-6.10-rc1 of git://git.kernel.org/pub/scm/linux/kernel/git/rafael/linux-pm") into android-mainline"

../vendor/mediatek/kernel_modules/met_drv_v3/common/met_thermal.c:95:15: error: incomplete definition of type struct thermal_zone_device
   95 |         if (tz->polling_delay_jiffies) {
      |             ~~^

[Test]
Build and Boot up

MTK-Commit-Id: a88fb2088e09834d0b00a14c5d331a8d834494fe

Signed-off-by: PoShao Chen <poshao.chen@mediatek.com>
CR-Id: ALPS08631203
Feature: Kernel SI Operation
Change-Id: Ib5953d90607da65f9f8ce6c23895e9c0aaa26b25